# Generated by Django 4.1.7 on 2023-02-19 13:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Ссылка')),
                ('photo', models.ImageField(upload_to='blog/', verbose_name='Заглавное изображение')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('description', models.TextField(verbose_name='Короткое описание')),
                ('full_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Полный текст')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ('date',),
            },
        ),
    ]
